packages:
  - "."

allowBuilds:
  "@heroui/shared-utils": true
  "@parcel/watcher": true
  electron-winstaller: true
  esbuild: true
  fsevents: true
  unrs-resolver: true
patchedDependencies:
  global-agent@4.1.3: patches/global-agent@4.1.3.patch
